---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: express-backend
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/sondresjolyst/Express-Backend-TypeScript-Example.git